//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Win32.TaskScheduler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Win32.TaskScheduler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any connection.
        /// </summary>
        internal static string AnyConnection {
            get {
                return ResourceManager.GetString("AnyConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This COM Class does not support the required interface..
        /// </summary>
        internal static string ComObjectDoesNotSupportInterfaceErrorMessage {
            get {
                return ResourceManager.GetString("ComObjectDoesNotSupportInterfaceErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize across time zones.
        /// </summary>
        internal static string DateTimeSyncText {
            get {
                return ResourceManager.GetString("DateTimeSyncText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Machine.
        /// </summary>
        internal static string LocalMachine {
            get {
                return ResourceManager.GetString("LocalMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Properties ({1}).
        /// </summary>
        internal static string TaskEditDlgTitle {
            get {
                return ResourceManager.GetString("TaskEditDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        internal static string TimeSpanDay {
            get {
                return ResourceManager.GetString("TimeSpanDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string TimeSpanDays {
            get {
                return ResourceManager.GetString("TimeSpanDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days,day,d.
        /// </summary>
        internal static string TimeSpanDayStrings {
            get {
                return ResourceManager.GetString("TimeSpanDayStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not wait.
        /// </summary>
        internal static string TimeSpanDoNotWait {
            get {
                return ResourceManager.GetString("TimeSpanDoNotWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        internal static string TimeSpanHour {
            get {
                return ResourceManager.GetString("TimeSpanHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string TimeSpanHours {
            get {
                return ResourceManager.GetString("TimeSpanHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours,hour,hrs,hr,h.
        /// </summary>
        internal static string TimeSpanHourStrings {
            get {
                return ResourceManager.GetString("TimeSpanHourStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immediately.
        /// </summary>
        internal static string TimeSpanImmediately {
            get {
                return ResourceManager.GetString("TimeSpanImmediately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indefinitely.
        /// </summary>
        internal static string TimeSpanIndefinitely {
            get {
                return ResourceManager.GetString("TimeSpanIndefinitely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        internal static string TimeSpanMinute {
            get {
                return ResourceManager.GetString("TimeSpanMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string TimeSpanMinutes {
            get {
                return ResourceManager.GetString("TimeSpanMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes,minute,mins,min,m.
        /// </summary>
        internal static string TimeSpanMinuteStrings {
            get {
                return ResourceManager.GetString("TimeSpanMinuteStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        internal static string TimeSpanMonth {
            get {
                return ResourceManager.GetString("TimeSpanMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        internal static string TimeSpanMonths {
            get {
                return ResourceManager.GetString("TimeSpanMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months,month,mos,mo,m.
        /// </summary>
        internal static string TimeSpanMonthStrings {
            get {
                return ResourceManager.GetString("TimeSpanMonthStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        internal static string TimeSpanSecond {
            get {
                return ResourceManager.GetString("TimeSpanSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string TimeSpanSeconds {
            get {
                return ResourceManager.GetString("TimeSpanSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds,second,secs,sec,s.
        /// </summary>
        internal static string TimeSpanSecondStrings {
            get {
                return ResourceManager.GetString("TimeSpanSecondStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        internal static string TimeSpanSeparator {
            get {
                return ResourceManager.GetString("TimeSpanSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        internal static string TimeSpanYear {
            get {
                return ResourceManager.GetString("TimeSpanYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        internal static string TimeSpanYears {
            get {
                return ResourceManager.GetString("TimeSpanYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years,year,yrs,yr,y.
        /// </summary>
        internal static string TimeSpanYearStrings {
            get {
                return ResourceManager.GetString("TimeSpanYearStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At startup.
        /// </summary>
        internal static string TriggerTypeBoot {
            get {
                return ResourceManager.GetString("TriggerTypeBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On an event.
        /// </summary>
        internal static string TriggerTypeEvent {
            get {
                return ResourceManager.GetString("TriggerTypeEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On idle.
        /// </summary>
        internal static string TriggerTypeIdle {
            get {
                return ResourceManager.GetString("TriggerTypeIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At log on.
        /// </summary>
        internal static string TriggerTypeLogon {
            get {
                return ResourceManager.GetString("TriggerTypeLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At task creation/modification.
        /// </summary>
        internal static string TriggerTypeRegistration {
            get {
                return ResourceManager.GetString("TriggerTypeRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On schedule.
        /// </summary>
        internal static string TriggerTypeSchedule {
            get {
                return ResourceManager.GetString("TriggerTypeSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On connection to a user session.
        /// </summary>
        internal static string TriggerTypeSessionConnect {
            get {
                return ResourceManager.GetString("TriggerTypeSessionConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On disconnect from a user session.
        /// </summary>
        internal static string TriggerTypeSessionDisconnect {
            get {
                return ResourceManager.GetString("TriggerTypeSessionDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On workstation lock.
        /// </summary>
        internal static string TriggerTypeWorkstationLock {
            get {
                return ResourceManager.GetString("TriggerTypeWorkstationLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On workstation unlock.
        /// </summary>
        internal static string TriggerTypeWorkstationUnlock {
            get {
                return ResourceManager.GetString("TriggerTypeWorkstationUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Event Trigger.
        /// </summary>
        internal static string WizardEventTriggerErrorTitle {
            get {
                return ResourceManager.GetString("WizardEventTriggerErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At a minimum, a log must be selected..
        /// </summary>
        internal static string WizardEventTriggerInvalid {
            get {
                return ResourceManager.GetString("WizardEventTriggerInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be at least one month, one week, and one weekday selected..
        /// </summary>
        internal static string WizardMonthlyDOWTriggerInvalid {
            get {
                return ResourceManager.GetString("WizardMonthlyDOWTriggerInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Monthly Trigger.
        /// </summary>
        internal static string WizardMonthlyTriggerErrorTitle {
            get {
                return ResourceManager.GetString("WizardMonthlyTriggerErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be at least one month and one day selected..
        /// </summary>
        internal static string WizardMonthlyTriggerInvalid {
            get {
                return ResourceManager.GetString("WizardMonthlyTriggerInvalid", resourceCulture);
            }
        }
    }
}
