//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Win32.TaskScheduler.EditorProperties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Win32.TaskScheduler.EditorProperties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Action.
        /// </summary>
        internal static string ActionDlgEditCaption {
            get {
                return ResourceManager.GetString("ActionDlgEditCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Action.
        /// </summary>
        internal static string ActionDlgNewCaption {
            get {
                return ResourceManager.GetString("ActionDlgNewCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom handler.
        /// </summary>
        internal static string ActionTypeComHandler {
            get {
                return ResourceManager.GetString("ActionTypeComHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ActionTypeComHandlerImage {
            get {
                object obj = ResourceManager.GetObject("ActionTypeComHandlerImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a program.
        /// </summary>
        internal static string ActionTypeExecute {
            get {
                return ResourceManager.GetString("ActionTypeExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ActionTypeExecuteImage {
            get {
                object obj = ResourceManager.GetObject("ActionTypeExecuteImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send an e-mail.
        /// </summary>
        internal static string ActionTypeSendEmail {
            get {
                return ResourceManager.GetString("ActionTypeSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ActionTypeSendEmailImage {
            get {
                object obj = ResourceManager.GetObject("ActionTypeSendEmailImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display a message.
        /// </summary>
        internal static string ActionTypeShowMessage {
            get {
                return ResourceManager.GetString("ActionTypeShowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ActionTypeShowMessageImage {
            get {
                object obj = ResourceManager.GetObject("ActionTypeShowMessageImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any connection.
        /// </summary>
        internal static string AnyConnection {
            get {
                return ResourceManager.GetString("AnyConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon auditFail {
            get {
                object obj = ResourceManager.GetObject("auditFail", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon auditSuccess {
            get {
                object obj = ResourceManager.GetObject("auditSuccess", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a new target computer:.
        /// </summary>
        internal static string BrowseForTargetServerPrompt {
            get {
                return ResourceManager.GetString("BrowseForTargetServerPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change User or Group....
        /// </summary>
        internal static string ChangeUserBtn {
            get {
                return ResourceManager.GetString("ChangeUserBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change User....
        /// </summary>
        internal static string ChangeUserBtnNonAdmin {
            get {
                return ResourceManager.GetString("ChangeUserBtnNonAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This COM Class does not support the required interface..
        /// </summary>
        internal static string ComObjectDoesNotSupportInterfaceErrorMessage {
            get {
                return ResourceManager.GetString("ComObjectDoesNotSupportInterfaceErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap createBasicTask {
            get {
                object obj = ResourceManager.GetObject("createBasicTask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter user account information for running this task..
        /// </summary>
        internal static string CredentialPromptMessage {
            get {
                return ResourceManager.GetString("CredentialPromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon critical {
            get {
                object obj = ResourceManager.GetObject("critical", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon d {
            get {
                object obj = ResourceManager.GetObject("d", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize across time zones.
        /// </summary>
        internal static string DateTimeSyncText {
            get {
                return ResourceManager.GetString("DateTimeSyncText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon disable {
            get {
                object obj = ResourceManager.GetObject("disable", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap downArrow {
            get {
                object obj = ResourceManager.GetObject("downArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap empty {
            get {
                object obj = ResourceManager.GetObject("empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon enable {
            get {
                object obj = ResourceManager.GetObject("enable", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon end {
            get {
                object obj = ResourceManager.GetObject("end", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This type of trigger cannot be edited in this tool..
        /// </summary>
        internal static string Error_CannotEditTrigger {
            get {
                return ResourceManager.GetString("Error_CannotEditTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve task history. Error: {0}.
        /// </summary>
        internal static string Error_CannotRetrieveHistory {
            get {
                return ResourceManager.GetString("Error_CannotRetrieveHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call to CredUIConfirmCredentials failed with error code: {0}.
        /// </summary>
        internal static string Error_CredUIConfirmFailed {
            get {
                return ResourceManager.GetString("Error_CredUIConfirmFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call to CredUIPromptForCredentials failed with error code: {0}.
        /// </summary>
        internal static string Error_CredUIPromptFailed {
            get {
                return ResourceManager.GetString("Error_CredUIPromptFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized text found in query XML..
        /// </summary>
        internal static string Error_EventFilterBadQuery {
            get {
                return ResourceManager.GetString("Error_EventFilterBadQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offending text: &apos;{0}&apos;.
        /// </summary>
        internal static string Error_EventFilterBadQueryText {
            get {
                return ResourceManager.GetString("Error_EventFilterBadQueryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task events and history are not supported on .NET versions prior to 3.5..
        /// </summary>
        internal static string Error_EventsNotSupported {
            get {
                return ResourceManager.GetString("Error_EventsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ID range pattern.
        /// </summary>
        internal static string Error_EventTriggerIDInvalid {
            get {
                return ResourceManager.GetString("Error_EventTriggerIDInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task name is not in a valid format. Characters not allowed in a filename are not allowed in a task name..
        /// </summary>
        internal static string Error_InvalidNameFormat {
            get {
                return ResourceManager.GetString("Error_InvalidNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropped content must be text or a file containing a valid Xml query..
        /// </summary>
        internal static string Error_InvalidQueryFormat {
            get {
                return ResourceManager.GetString("Error_InvalidQueryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDDL must be in format defined at http://goo.gl/6au0V.
        /// </summary>
        internal static string Error_InvalidSddlFormat {
            get {
                return ResourceManager.GetString("Error_InvalidSddlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid duration value..
        /// </summary>
        internal static string Error_InvalidSpanValue {
            get {
                return ResourceManager.GetString("Error_InvalidSpanValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URI is not in a correct format.
        /// </summary>
        internal static string Error_InvalidUriFormat {
            get {
                return ResourceManager.GetString("Error_InvalidUriFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version must be in the format major.minor[.build[.revision]]..
        /// </summary>
        internal static string Error_InvalidVersionFormat {
            get {
                return ResourceManager.GetString("Error_InvalidVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum deadline or period a task can use is 1 day. The deadline must also be greater than the period..
        /// </summary>
        internal static string Error_MaintenanceDeadlineLimit {
            get {
                return ResourceManager.GetString("Error_MaintenanceDeadlineLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running a task under a group user account is supported only on Windows Vista™ or later. To run a task under a group account, you must upgrade this task to a Windows Vista™ task..
        /// </summary>
        internal static string Error_NoGroupsUnderV1 {
            get {
                return ResourceManager.GetString("Error_NoGroupsUnderV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Scheduler cannot create the task. The user account is unknown, the password is incorrect, or the user account does not have permission to create this task..
        /// </summary>
        internal static string Error_PasswordMustBeProvided {
            get {
                return ResourceManager.GetString("Error_PasswordMustBeProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user account on the General tab must be set to either &apos;NETWORK SERVICE&apos; or &apos;LOCAL SERVICE&apos; when the Process SID Type is set to &apos;Unrestricted&apos; on the Additions tab. You must either change the SID Type or set the user to one of the valid accounts..
        /// </summary>
        internal static string Error_PrincipalSidTypeInvalid {
            get {
                return ResourceManager.GetString("Error_PrincipalSidTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The repetition duration value must be 1 minute or greater..
        /// </summary>
        internal static string Error_RepetitionDurationOutOfRange {
            get {
                return ResourceManager.GetString("Error_RepetitionDurationOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The repetition interval value must be 1 minute or greater and less than or equal to 31 days..
        /// </summary>
        internal static string Error_RepetitionIntervalOutOfRange {
            get {
                return ResourceManager.GetString("Error_RepetitionIntervalOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The repetition interval value must be less than or equal to the repetition duration value..
        /// </summary>
        internal static string Error_RepetitionMoreThanDuration {
            get {
                return ResourceManager.GetString("Error_RepetitionMoreThanDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to have a task deleted automatically after it runs, you must add at least one trigger that has an expiration date..
        /// </summary>
        internal static string Error_TaskDeleteMustHaveExpiringTrigger {
            get {
                return ResourceManager.GetString("Error_TaskDeleteMustHaveExpiringTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following property settings cannot be used with the selected compatibility setting:.
        /// </summary>
        internal static string Error_TaskPropertiesIncompatible {
            get {
                return ResourceManager.GetString("Error_TaskPropertiesIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some settings are incompatible with this selection..
        /// </summary>
        internal static string Error_TaskPropertiesIncompatibleSimple {
            get {
                return ResourceManager.GetString("Error_TaskPropertiesIncompatibleSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event {0}, TaskScheduler.
        /// </summary>
        internal static string EventDetailHeader {
            get {
                return ResourceManager.GetString("EventDetailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;All Keywords&gt;.
        /// </summary>
        internal static string EventKeywordsAll {
            get {
                return ResourceManager.GetString("EventKeywordsAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Failure.
        /// </summary>
        internal static string EventKeywordsAuditFailure {
            get {
                return ResourceManager.GetString("EventKeywordsAuditFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Success.
        /// </summary>
        internal static string EventKeywordsAuditSuccess {
            get {
                return ResourceManager.GetString("EventKeywordsAuditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correlation Hint.
        /// </summary>
        internal static string EventKeywordsCorrelationHint2 {
            get {
                return ResourceManager.GetString("EventKeywordsCorrelationHint2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic.
        /// </summary>
        internal static string EventKeywordsEventLogClassic {
            get {
                return ResourceManager.GetString("EventKeywordsEventLogClassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Time.
        /// </summary>
        internal static string EventKeywordsResponseTime {
            get {
                return ResourceManager.GetString("EventKeywordsResponseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQM.
        /// </summary>
        internal static string EventKeywordsSqm {
            get {
                return ResourceManager.GetString("EventKeywordsSqm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WDI Context.
        /// </summary>
        internal static string EventKeywordsWdiContext {
            get {
                return ResourceManager.GetString("EventKeywordsWdiContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WDI Diag.
        /// </summary>
        internal static string EventKeywordsWdiDiagnostic {
            get {
                return ResourceManager.GetString("EventKeywordsWdiDiagnostic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications and Services Logs.
        /// </summary>
        internal static string EventLogParentApps {
            get {
                return ResourceManager.GetString("EventLogParentApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Logs.
        /// </summary>
        internal static string EventLogParentStandard {
            get {
                return ResourceManager.GetString("EventLogParentStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;All Logs&gt;.
        /// </summary>
        internal static string EventLogsAll {
            get {
                return ResourceManager.GetString("EventLogsAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 12 hours.
        /// </summary>
        internal static string EventLogTime12Hours {
            get {
                return ResourceManager.GetString("EventLogTime12Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 30 days.
        /// </summary>
        internal static string EventLogTime30Days {
            get {
                return ResourceManager.GetString("EventLogTime30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any time.
        /// </summary>
        internal static string EventLogTimeAnyTime {
            get {
                return ResourceManager.GetString("EventLogTimeAnyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom range....
        /// </summary>
        internal static string EventLogTimeCustom {
            get {
                return ResourceManager.GetString("EventLogTimeCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Events from {0}.
        /// </summary>
        internal static string EventLogTimeCustomFrom {
            get {
                return ResourceManager.GetString("EventLogTimeCustomFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From {0} to {1}.
        /// </summary>
        internal static string EventLogTimeCustomFromTo {
            get {
                return ResourceManager.GetString("EventLogTimeCustomFromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Events up to {1}.
        /// </summary>
        internal static string EventLogTimeCustomTo {
            get {
                return ResourceManager.GetString("EventLogTimeCustomTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 24 hours.
        /// </summary>
        internal static string EventLogTimeDay {
            get {
                return ResourceManager.GetString("EventLogTimeDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last hour.
        /// </summary>
        internal static string EventLogTimeHour {
            get {
                return ResourceManager.GetString("EventLogTimeHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 7 days.
        /// </summary>
        internal static string EventLogTimeWeek {
            get {
                return ResourceManager.GetString("EventLogTimeWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Properties - Event {0}, TaskScheduler.
        /// </summary>
        internal static string EventPropertiesDialogTitle {
            get {
                return ResourceManager.GetString("EventPropertiesDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;All Sources&gt;.
        /// </summary>
        internal static string EventSourcesAll {
            get {
                return ResourceManager.GetString("EventSourcesAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;All Task Categories&gt;.
        /// </summary>
        internal static string EventTasksAll {
            get {
                return ResourceManager.GetString("EventTasksAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you choose to manually edit the query, you will no longer be able to modify the query using the controls on the Filter tab. Would you like to continue?.
        /// </summary>
        internal static string EventTriggerFilterGoManualPrompt {
            get {
                return ResourceManager.GetString("EventTriggerFilterGoManualPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to use the Filter tab to edit the query ? This will result in manual changes made to the query being discarded..
        /// </summary>
        internal static string EventTriggerFilterUseFormPrompt {
            get {
                return ResourceManager.GetString("EventTriggerFilterUseFormPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Viewer.
        /// </summary>
        internal static string EventViewerDialogTitle {
            get {
                return ResourceManager.GetString("EventViewerDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon filter {
            get {
                object obj = ResourceManager.GetObject("filter", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap filterBmp {
            get {
                object obj = ResourceManager.GetObject("filterBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon helpBook {
            get {
                object obj = ResourceManager.GetObject("helpBook", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of events: {0}.
        /// </summary>
        internal static string HistoryHeader {
            get {
                return ResourceManager.GetString("HistoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon infoBubble {
            get {
                object obj = ResourceManager.GetObject("infoBubble", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task is currently running. (0x{0:X}).
        /// </summary>
        internal static string LastResultRunning {
            get {
                return ResourceManager.GetString("LastResultRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation completed successfully. (0x0).
        /// </summary>
        internal static string LastResultSuccessful {
            get {
                return ResourceManager.GetString("LastResultSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string LoadingPrompt {
            get {
                return ResourceManager.GetString("LoadingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Machine.
        /// </summary>
        internal static string LocalMachine {
            get {
                return ResourceManager.GetString("LocalMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minus {
            get {
                object obj = ResourceManager.GetObject("minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        internal static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;none&gt;.
        /// </summary>
        internal static string NoUserSpecifiedText {
            get {
                return ResourceManager.GetString("NoUserSpecifiedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plus {
            get {
                object obj = ResourceManager.GetObject("plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above normal.
        /// </summary>
        internal static string ProcessPriorityAboveNormal {
            get {
                return ResourceManager.GetString("ProcessPriorityAboveNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below normal.
        /// </summary>
        internal static string ProcessPriorityBelowNormal {
            get {
                return ResourceManager.GetString("ProcessPriorityBelowNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string ProcessPriorityHigh {
            get {
                return ResourceManager.GetString("ProcessPriorityHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        internal static string ProcessPriorityIdle {
            get {
                return ResourceManager.GetString("ProcessPriorityIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string ProcessPriorityNormal {
            get {
                return ResourceManager.GetString("ProcessPriorityNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-time.
        /// </summary>
        internal static string ProcessPriorityRealTime {
            get {
                return ResourceManager.GetString("ProcessPriorityRealTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon question {
            get {
                object obj = ResourceManager.GetObject("question", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon run {
            get {
                object obj = ResourceManager.GetObject("run", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string SIDTypeDefault {
            get {
                return ResourceManager.GetString("SIDTypeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string SIDTypeNone {
            get {
                return ResourceManager.GetString("SIDTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrestricted.
        /// </summary>
        internal static string SIDTypeUnrestricted {
            get {
                return ResourceManager.GetString("SIDTypeUnrestricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AT service|Windows Server™ 2003, Windows® XP, or Windows® 2000|Windows Vista™, Windows Server™ 2008|Windows® 7, Windows Server™ 2008 R2|Windows® 8 or 8.1, Windows Server™ 2012|Windows®10.
        /// </summary>
        internal static string TaskCompatibility {
            get {
                return ResourceManager.GetString("TaskCompatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Properties ({1}).
        /// </summary>
        internal static string TaskEditDlgTitle {
            get {
                return ResourceManager.GetString("TaskEditDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        internal static string TaskEventStatusFailure {
            get {
                return ResourceManager.GetString("TaskEventStatusFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still running.
        /// </summary>
        internal static string TaskEventStatusStillRunning {
            get {
                return ResourceManager.GetString("TaskEventStatusStillRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string TaskEventStatusSuccess {
            get {
                return ResourceManager.GetString("TaskEventStatusSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminated.
        /// </summary>
        internal static string TaskEventStatusTerminated {
            get {
                return ResourceManager.GetString("TaskEventStatusTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not start a new instance.
        /// </summary>
        internal static string TaskInstancesIgnoreNew {
            get {
                return ResourceManager.GetString("TaskInstancesIgnoreNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run a new instance in parallel.
        /// </summary>
        internal static string TaskInstancesParallel {
            get {
                return ResourceManager.GetString("TaskInstancesParallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue a new instance.
        /// </summary>
        internal static string TaskInstancesQueue {
            get {
                return ResourceManager.GetString("TaskInstancesQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop the existing instance.
        /// </summary>
        internal static string TaskInstancesStopExisting {
            get {
                return ResourceManager.GetString("TaskInstancesStopExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be at least one action assigned to this task..
        /// </summary>
        internal static string TaskMustHaveActionsError {
            get {
                return ResourceManager.GetString("TaskMustHaveActionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Run Times ({0}).
        /// </summary>
        internal static string TaskRunTimesDialogTitle {
            get {
                return ResourceManager.GetString("TaskRunTimesDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Scheduler.
        /// </summary>
        internal static string TaskSchedulerName {
            get {
                return ResourceManager.GetString("TaskSchedulerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not wait.
        /// </summary>
        internal static string TimeSpanDoNotWait {
            get {
                return ResourceManager.GetString("TimeSpanDoNotWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immediately.
        /// </summary>
        internal static string TimeSpanImmediately {
            get {
                return ResourceManager.GetString("TimeSpanImmediately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indefinitely.
        /// </summary>
        internal static string TimeSpanIndefinitely {
            get {
                return ResourceManager.GetString("TimeSpanIndefinitely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not started.
        /// </summary>
        internal static string TimeSpanNotStarted {
            get {
                return ResourceManager.GetString("TimeSpanNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unset.
        /// </summary>
        internal static string TimeSpanUnset {
            get {
                return ResourceManager.GetString("TimeSpanUnset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Trigger.
        /// </summary>
        internal static string TriggerDlgEditCaption {
            get {
                return ResourceManager.GetString("TriggerDlgEditCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Trigger.
        /// </summary>
        internal static string TriggerDlgNewCaption {
            get {
                return ResourceManager.GetString("TriggerDlgNewCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At startup.
        /// </summary>
        internal static string TriggerTypeBoot {
            get {
                return ResourceManager.GetString("TriggerTypeBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TriggerTypeBootImage {
            get {
                object obj = ResourceManager.GetObject("TriggerTypeBootImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Trigger.
        /// </summary>
        internal static string TriggerTypeCustom {
            get {
                return ResourceManager.GetString("TriggerTypeCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TriggerTypeCustomImage {
            get {
                object obj = ResourceManager.GetObject("TriggerTypeCustomImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TriggerTypeDailyImage {
            get {
                object obj = ResourceManager.GetObject("TriggerTypeDailyImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On an event.
        /// </summary>
        internal static string TriggerTypeEvent {
            get {
                return ResourceManager.GetString("TriggerTypeEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TriggerTypeEventImage {
            get {
                object obj = ResourceManager.GetObject("TriggerTypeEventImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On idle.
        /// </summary>
        internal static string TriggerTypeIdle {
            get {
                return ResourceManager.GetString("TriggerTypeIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TriggerTypeIdleImage {
            get {
                object obj = ResourceManager.GetObject("TriggerTypeIdleImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At log on.
        /// </summary>
        internal static string TriggerTypeLogon {
            get {
                return ResourceManager.GetString("TriggerTypeLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TriggerTypeLogonImage {
            get {
                object obj = ResourceManager.GetObject("TriggerTypeLogonImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TriggerTypeMonthlyDOWImage {
            get {
                object obj = ResourceManager.GetObject("TriggerTypeMonthlyDOWImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TriggerTypeMonthlyImage {
            get {
                object obj = ResourceManager.GetObject("TriggerTypeMonthlyImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At task creation/modification.
        /// </summary>
        internal static string TriggerTypeRegistration {
            get {
                return ResourceManager.GetString("TriggerTypeRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TriggerTypeRegistrationImage {
            get {
                object obj = ResourceManager.GetObject("TriggerTypeRegistrationImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On connection to a remote user session.
        /// </summary>
        internal static string TriggerTypeRemoteConnect {
            get {
                return ResourceManager.GetString("TriggerTypeRemoteConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On disconnect from a remote user session.
        /// </summary>
        internal static string TriggerTypeRemoteDisconnect {
            get {
                return ResourceManager.GetString("TriggerTypeRemoteDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On a schedule.
        /// </summary>
        internal static string TriggerTypeSchedule {
            get {
                return ResourceManager.GetString("TriggerTypeSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On connection to a user session.
        /// </summary>
        internal static string TriggerTypeSessionConnect {
            get {
                return ResourceManager.GetString("TriggerTypeSessionConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On disconnect from a user session.
        /// </summary>
        internal static string TriggerTypeSessionDisconnect {
            get {
                return ResourceManager.GetString("TriggerTypeSessionDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TriggerTypeSessionStateChangeImage {
            get {
                object obj = ResourceManager.GetObject("TriggerTypeSessionStateChangeImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TriggerTypeStateDisabled {
            get {
                object obj = ResourceManager.GetObject("TriggerTypeStateDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TriggerTypeTimeImage {
            get {
                object obj = ResourceManager.GetObject("TriggerTypeTimeImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TriggerTypeWeeklyImage {
            get {
                object obj = ResourceManager.GetObject("TriggerTypeWeeklyImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On workstation lock.
        /// </summary>
        internal static string TriggerTypeWorkstationLock {
            get {
                return ResourceManager.GetString("TriggerTypeWorkstationLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On workstation unlock.
        /// </summary>
        internal static string TriggerTypeWorkstationUnlock {
            get {
                return ResourceManager.GetString("TriggerTypeWorkstationUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ts {
            get {
                object obj = ResourceManager.GetObject("ts", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tsBmp {
            get {
                object obj = ResourceManager.GetObject("tsBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon tsFolderClosed {
            get {
                object obj = ResourceManager.GetObject("tsFolderClosed", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon tsFolderOpen {
            get {
                object obj = ResourceManager.GetObject("tsFolderOpen", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon tsList {
            get {
                object obj = ResourceManager.GetObject("tsList", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon tsNew {
            get {
                object obj = ResourceManager.GetObject("tsNew", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap undo {
            get {
                object obj = ResourceManager.GetObject("undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap upArrow {
            get {
                object obj = ResourceManager.GetObject("upArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid password for the specified account was not provided..
        /// </summary>
        internal static string UserAuthenticationError {
            get {
                return ResourceManager.GetString("UserAuthenticationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting this property will disable a number of other properties. Would you still like to proceed?.
        /// </summary>
        internal static string UseUnifiedResetQuestion {
            get {
                return ResourceManager.GetString("UseUnifiedResetQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon verbose {
            get {
                object obj = ResourceManager.GetObject("verbose", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sends an e-mail using supplied information..
        /// </summary>
        internal static string WizActionSubtextEmail {
            get {
                return ResourceManager.GetString("WizActionSubtextEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executes a command-line operation..
        /// </summary>
        internal static string WizActionSubtextExecute {
            get {
                return ResourceManager.GetString("WizActionSubtextExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a message box when a task is activated..
        /// </summary>
        internal static string WizActionSubtextShowMessage {
            get {
                return ResourceManager.GetString("WizActionSubtextShowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run a program.
        /// </summary>
        internal static string WizActionTextExecute {
            get {
                return ResourceManager.GetString("WizActionTextExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send an e-mail.
        /// </summary>
        internal static string WizActionTextSendEmail {
            get {
                return ResourceManager.GetString("WizActionTextSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display a message.
        /// </summary>
        internal static string WizActionTextShowMessage {
            get {
                return ResourceManager.GetString("WizActionTextShowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Event Trigger.
        /// </summary>
        internal static string WizardEventTriggerErrorTitle {
            get {
                return ResourceManager.GetString("WizardEventTriggerErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At a minimum, a log must be selected..
        /// </summary>
        internal static string WizardEventTriggerInvalid {
            get {
                return ResourceManager.GetString("WizardEventTriggerInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be at least one month, one week, and one weekday selected..
        /// </summary>
        internal static string WizardMonthlyDOWTriggerInvalid {
            get {
                return ResourceManager.GetString("WizardMonthlyDOWTriggerInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Monthly Trigger.
        /// </summary>
        internal static string WizardMonthlyTriggerErrorTitle {
            get {
                return ResourceManager.GetString("WizardMonthlyTriggerErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be at least one month and one day selected..
        /// </summary>
        internal static string WizardMonthlyTriggerInvalid {
            get {
                return ResourceManager.GetString("WizardMonthlyTriggerInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {0}
        ///
        ///Description: {1}
        ///
        ///Trigger: {2}
        ///
        ///Action: {3}.
        /// </summary>
        internal static string WizardSummaryFormatString {
            get {
                return ResourceManager.GetString("WizardSummaryFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts a task based on a daily schedule. For example, the task starts at a specific time every day, every other day, every third day, and so on..
        /// </summary>
        internal static string WizTriggerSubtextDaily {
            get {
                return ResourceManager.GetString("WizTriggerSubtextDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts a task when a system event occurs..
        /// </summary>
        internal static string WizTriggerSubtextEvent {
            get {
                return ResourceManager.GetString("WizTriggerSubtextEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts a task based on a monthly schedule. For example, the task starts on specific days of specific months..
        /// </summary>
        internal static string WizTriggerSubtextMonthly {
            get {
                return ResourceManager.GetString("WizTriggerSubtextMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts a task at a specific date and time..
        /// </summary>
        internal static string WizTriggerSubtextTime {
            get {
                return ResourceManager.GetString("WizTriggerSubtextTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts a task based on a weekly schedule. For example, the task starts at 8:00 A.M. on a specific day of the week every week or every other week..
        /// </summary>
        internal static string WizTriggerSubtextWeekly {
            get {
                return ResourceManager.GetString("WizTriggerSubtextWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string WizTriggerTextDaily {
            get {
                return ResourceManager.GetString("WizTriggerTextDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a specific event is logged.
        /// </summary>
        internal static string WizTriggerTextEvent {
            get {
                return ResourceManager.GetString("WizTriggerTextEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string WizTriggerTextMonthly {
            get {
                return ResourceManager.GetString("WizTriggerTextMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One time.
        /// </summary>
        internal static string WizTriggerTextTime {
            get {
                return ResourceManager.GetString("WizTriggerTextTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string WizTriggerTextWeekly {
            get {
                return ResourceManager.GetString("WizTriggerTextWeekly", resourceCulture);
            }
        }
    }
}
