//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecurityEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow.
        /// </summary>
        internal static string AccessControlTypeAllow {
            get {
                return ResourceManager.GetString("AccessControlTypeAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny.
        /// </summary>
        internal static string AccessControlTypeDeny {
            get {
                return ResourceManager.GetString("AccessControlTypeDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder only.
        /// </summary>
        internal static string FileSystem {
            get {
                return ResourceManager.GetString("FileSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder and subfolders.
        /// </summary>
        internal static string FileSystemCI {
            get {
                return ResourceManager.GetString("FileSystemCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder, subfolders and files.
        /// </summary>
        internal static string FileSystemCIOI {
            get {
                return ResourceManager.GetString("FileSystemCIOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subfolders only.
        /// </summary>
        internal static string FileSystemIOCI {
            get {
                return ResourceManager.GetString("FileSystemIOCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subfolders and files only.
        /// </summary>
        internal static string FileSystemIOCIOI {
            get {
                return ResourceManager.GetString("FileSystemIOCIOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files only.
        /// </summary>
        internal static string FileSystemIOOI {
            get {
                return ResourceManager.GetString("FileSystemIOOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder and files.
        /// </summary>
        internal static string FileSystemOI {
            get {
                return ResourceManager.GetString("FileSystemOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full control.
        /// </summary>
        internal static string FileSystemRightsFullControl {
            get {
                return ResourceManager.GetString("FileSystemRightsFullControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        internal static string FileSystemRightsModify {
            get {
                return ResourceManager.GetString("FileSystemRightsModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        internal static string FileSystemRightsRead {
            get {
                return ResourceManager.GetString("FileSystemRightsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read &amp; execute.
        /// </summary>
        internal static string FileSystemRightsReadAndExecute {
            get {
                return ResourceManager.GetString("FileSystemRightsReadAndExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read, write &amp; execute.
        /// </summary>
        internal static string FileSystemRightsReadWriteExecute {
            get {
                return ResourceManager.GetString("FileSystemRightsReadWriteExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize.
        /// </summary>
        internal static string FileSystemRightsSynchronize {
            get {
                return ResourceManager.GetString("FileSystemRightsSynchronize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write.
        /// </summary>
        internal static string FileSystemRightsWrite {
            get {
                return ResourceManager.GetString("FileSystemRightsWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Group {
            get {
                object obj = ResourceManager.GetObject("Group", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Information {
            get {
                object obj = ResourceManager.GetObject("Information", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        internal static string Special {
            get {
                return ResourceManager.GetString("Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special permissions.
        /// </summary>
        internal static string SpecialPermissions {
            get {
                return ResourceManager.GetString("SpecialPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon User {
            get {
                object obj = ResourceManager.GetObject("User", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
