//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskSchedulerConfig.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskSchedulerConfig.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File and Printer Sharing.
        /// </summary>
        internal static string FileAndPrinterSharingRule {
            get {
                return ResourceManager.GetString("FileAndPrinterSharingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firewall is enabled.
        /// </summary>
        internal static string FirewallEnabled {
            get {
                return ResourceManager.GetString("FirewallEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firewall rule &apos;{0}&apos; is enabled.
        /// </summary>
        internal static string FirewallRuleEnabled {
            get {
                return ResourceManager.GetString("FirewallRuleEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Information.
        /// </summary>
        internal static string GroupGeneral {
            get {
                return ResourceManager.GetString("GroupGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 1 (XP/Server 2000).
        /// </summary>
        internal static string GroupV1 {
            get {
                return ResourceManager.GetString("GroupV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 2 (Vista/2003 and later).
        /// </summary>
        internal static string GroupV2 {
            get {
                return ResourceManager.GetString("GroupV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Minus {
            get {
                object obj = ResourceManager.GetObject("Minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plus {
            get {
                object obj = ResourceManager.GetObject("Plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Remote Registry&quot; service is running.
        /// </summary>
        internal static string RemoteRegistryServiceRunning {
            get {
                return ResourceManager.GetString("RemoteRegistryServiceRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Scheduled Tasks Management.
        /// </summary>
        internal static string RemoteTaskManagementRule {
            get {
                return ResourceManager.GetString("RemoteTaskManagementRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap restarrow {
            get {
                object obj = ResourceManager.GetObject("restarrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap selarrow {
            get {
                object obj = ResourceManager.GetObject("selarrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shield {
            get {
                object obj = ResourceManager.GetObject("shield", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ts {
            get {
                object obj = ResourceManager.GetObject("ts", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos; is a member of at least one of the required groups.
        /// </summary>
        internal static string UserHasCorrectRights {
            get {
                return ResourceManager.GetString("UserHasCorrectRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has access rights to C:\Windows\Tasks.
        /// </summary>
        internal static string UserHasPathAccess {
            get {
                return ResourceManager.GetString("UserHasPathAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos; is a member of the Administrators group.
        /// </summary>
        internal static string UserIsAdmin {
            get {
                return ResourceManager.GetString("UserIsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos; is a member of the Backup Operators group.
        /// </summary>
        internal static string UserIsBackupOperator {
            get {
                return ResourceManager.GetString("UserIsBackupOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos; is a member of the Server Operators group.
        /// </summary>
        internal static string UserIsServerOperator {
            get {
                return ResourceManager.GetString("UserIsServerOperator", resourceCulture);
            }
        }
    }
}
