//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Win32.TaskScheduler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Win32.TaskScheduler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Action.
        /// </summary>
        internal static string ActionDlgEditCaption {
            get {
                return ResourceManager.GetString("ActionDlgEditCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Action.
        /// </summary>
        internal static string ActionDlgNewCaption {
            get {
                return ResourceManager.GetString("ActionDlgNewCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any connection.
        /// </summary>
        internal static string AnyConnection {
            get {
                return ResourceManager.GetString("AnyConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a new target computer:.
        /// </summary>
        internal static string BrowseForTargetServerPrompt {
            get {
                return ResourceManager.GetString("BrowseForTargetServerPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This COM Class does not support the required interface..
        /// </summary>
        internal static string ComObjectDoesNotSupportInterfaceErrorMessage {
            get {
                return ResourceManager.GetString("ComObjectDoesNotSupportInterfaceErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter user account information for running this task..
        /// </summary>
        internal static string CredentialPromptMessage {
            get {
                return ResourceManager.GetString("CredentialPromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize across time zones.
        /// </summary>
        internal static string DateTimeSyncText {
            get {
                return ResourceManager.GetString("DateTimeSyncText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call to CredUIConfirmCredentials failed with error code: {0}.
        /// </summary>
        internal static string Error_CredUIConfirmFailed {
            get {
                return ResourceManager.GetString("Error_CredUIConfirmFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call to CredUIPromptForCredentials failed with error code: {0}.
        /// </summary>
        internal static string Error_CredUIPromptFailed {
            get {
                return ResourceManager.GetString("Error_CredUIPromptFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to have a task deleted automatically after it runs, you must add at least one trigger that has an expiration date..
        /// </summary>
        internal static string Error_TaskDeleteMustHaveExpiringTrigger {
            get {
                return ResourceManager.GetString("Error_TaskDeleteMustHaveExpiringTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation completed successfully. (0x0).
        /// </summary>
        internal static string LastResultSuccessful {
            get {
                return ResourceManager.GetString("LastResultSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Machine.
        /// </summary>
        internal static string LocalMachine {
            get {
                return ResourceManager.GetString("LocalMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        internal static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;none&gt;.
        /// </summary>
        internal static string NoUserSpecifiedText {
            get {
                return ResourceManager.GetString("NoUserSpecifiedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Properties ({1}).
        /// </summary>
        internal static string TaskEditDlgTitle {
            get {
                return ResourceManager.GetString("TaskEditDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be at least one action assigned to this task..
        /// </summary>
        internal static string TaskMustHaveActionsError {
            get {
                return ResourceManager.GetString("TaskMustHaveActionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Run Times ({0}).
        /// </summary>
        internal static string TaskRunTimesDialogTitle {
            get {
                return ResourceManager.GetString("TaskRunTimesDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Scheduler.
        /// </summary>
        internal static string TaskSchedulerName {
            get {
                return ResourceManager.GetString("TaskSchedulerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not wait.
        /// </summary>
        internal static string TimeSpanDoNotWait {
            get {
                return ResourceManager.GetString("TimeSpanDoNotWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immediately.
        /// </summary>
        internal static string TimeSpanImmediately {
            get {
                return ResourceManager.GetString("TimeSpanImmediately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indefinitely.
        /// </summary>
        internal static string TimeSpanIndefinitely {
            get {
                return ResourceManager.GetString("TimeSpanIndefinitely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Trigger.
        /// </summary>
        internal static string TriggerDlgEditCaption {
            get {
                return ResourceManager.GetString("TriggerDlgEditCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Trigger.
        /// </summary>
        internal static string TriggerDlgNewCaption {
            get {
                return ResourceManager.GetString("TriggerDlgNewCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At startup.
        /// </summary>
        internal static string TriggerTypeBoot {
            get {
                return ResourceManager.GetString("TriggerTypeBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On an event.
        /// </summary>
        internal static string TriggerTypeEvent {
            get {
                return ResourceManager.GetString("TriggerTypeEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On idle.
        /// </summary>
        internal static string TriggerTypeIdle {
            get {
                return ResourceManager.GetString("TriggerTypeIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At log on.
        /// </summary>
        internal static string TriggerTypeLogon {
            get {
                return ResourceManager.GetString("TriggerTypeLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At task creation/modification.
        /// </summary>
        internal static string TriggerTypeRegistration {
            get {
                return ResourceManager.GetString("TriggerTypeRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On a schedule.
        /// </summary>
        internal static string TriggerTypeSchedule {
            get {
                return ResourceManager.GetString("TriggerTypeSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On connection to a user session.
        /// </summary>
        internal static string TriggerTypeSessionConnect {
            get {
                return ResourceManager.GetString("TriggerTypeSessionConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On disconnect from a user session.
        /// </summary>
        internal static string TriggerTypeSessionDisconnect {
            get {
                return ResourceManager.GetString("TriggerTypeSessionDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On workstation lock.
        /// </summary>
        internal static string TriggerTypeWorkstationLock {
            get {
                return ResourceManager.GetString("TriggerTypeWorkstationLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On workstation unlock.
        /// </summary>
        internal static string TriggerTypeWorkstationUnlock {
            get {
                return ResourceManager.GetString("TriggerTypeWorkstationUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid password for the specified account was not provided..
        /// </summary>
        internal static string UserAuthenticationError {
            get {
                return ResourceManager.GetString("UserAuthenticationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Event Trigger.
        /// </summary>
        internal static string WizardEventTriggerErrorTitle {
            get {
                return ResourceManager.GetString("WizardEventTriggerErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At a minimum, a log must be selected..
        /// </summary>
        internal static string WizardEventTriggerInvalid {
            get {
                return ResourceManager.GetString("WizardEventTriggerInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be at least one month, one week, and one weekday selected..
        /// </summary>
        internal static string WizardMonthlyDOWTriggerInvalid {
            get {
                return ResourceManager.GetString("WizardMonthlyDOWTriggerInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Monthly Trigger.
        /// </summary>
        internal static string WizardMonthlyTriggerErrorTitle {
            get {
                return ResourceManager.GetString("WizardMonthlyTriggerErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be at least one month and one day selected..
        /// </summary>
        internal static string WizardMonthlyTriggerInvalid {
            get {
                return ResourceManager.GetString("WizardMonthlyTriggerInvalid", resourceCulture);
            }
        }
    }
}
